[
  {
    name: `Components`,
    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components`,
    innerPath: `Components`,
    structure: [
      {
        name: `Common`,
        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Common`,
        innerPath: `Components/Common`,
        structure: [
          {
            name: `Header`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Common/Header`,
            innerPath: `Components/Common/Header`,
            structure: [
              {
                name: `HeaderLink`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Common/Header/HeaderLink`,
                innerPath: `Components/Common/Header/HeaderLink`,
                structure: [
                  {
                    name: `index`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Common/Header/HeaderLink/index.tsx`,
                    innerPath: `Components/Common/Header/HeaderLink/index.tsx`,
                    isDirectory: false,
                    isFile: true,
                  },
                ],
                isDirectory: true,
                isFile: false,
              },
              {
                name: `index`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Common/Header/index.tsx`,
                innerPath: `Components/Common/Header/index.tsx`,
                isDirectory: false,
                isFile: true,
              },
            ],
            isDirectory: true,
            isFile: false,
          },
          {
            name: `index`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Common/index.ts`,
            innerPath: `Components/Common/index.ts`,
            isDirectory: false,
            isFile: true,
          },
        ],
        isDirectory: true,
        isFile: false,
      },
      {
        name: `Design`,
        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Design`,
        innerPath: `Components/Design`,
        structure: [
          {
            name: `Button`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Design/Button`,
            innerPath: `Components/Design/Button`,
            structure: [
              {
                name: `__stories__`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Design/Button/__stories__`,
                innerPath: `Components/Design/Button/__stories__`,
                structure: [
                  {
                    name: `Button`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Design/Button/__stories__/Button.story.tsx`,
                    innerPath: `Components/Design/Button/__stories__/Button.story.tsx`,
                    isDirectory: false,
                    isFile: true,
                  },
                ],
                isDirectory: true,
                isFile: false,
              },
              {
                name: `index`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Design/Button/index.tsx`,
                innerPath: `Components/Design/Button/index.tsx`,
                isDirectory: false,
                isFile: true,
              },
            ],
            isDirectory: true,
            isFile: false,
          },
          {
            name: `Tile`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Design/Tile`,
            innerPath: `Components/Design/Tile`,
            structure: [
              {
                name: `__stories__`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Design/Tile/__stories__`,
                innerPath: `Components/Design/Tile/__stories__`,
                structure: [
                  {
                    name: `Tile`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Design/Tile/__stories__/Tile.story.tsx`,
                    innerPath: `Components/Design/Tile/__stories__/Tile.story.tsx`,
                    isDirectory: false,
                    isFile: true,
                  },
                ],
                isDirectory: true,
                isFile: false,
              },
              {
                name: `index`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Design/Tile/index.tsx`,
                innerPath: `Components/Design/Tile/index.tsx`,
                isDirectory: false,
                isFile: true,
              },
            ],
            isDirectory: true,
            isFile: false,
          },
          {
            name: `TileWithMarkdown`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Design/TileWithMarkdown`,
            innerPath: `Components/Design/TileWithMarkdown`,
            structure: [
              {
                name: `__stories__`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Design/TileWithMarkdown/__stories__`,
                innerPath: `Components/Design/TileWithMarkdown/__stories__`,
                structure: [
                  {
                    name: `TileWithMarkdown`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Design/TileWithMarkdown/__stories__/TileWithMarkdown.story.tsx`,
                    innerPath: `Components/Design/TileWithMarkdown/__stories__/TileWithMarkdown.story.tsx`,
                    isDirectory: false,
                    isFile: true,
                  },
                ],
                isDirectory: true,
                isFile: false,
              },
              {
                name: `index`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Design/TileWithMarkdown/index.tsx`,
                innerPath: `Components/Design/TileWithMarkdown/index.tsx`,
                isDirectory: false,
                isFile: true,
              },
            ],
            isDirectory: true,
            isFile: false,
          },
          {
            name: `index`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Design/index.ts`,
            innerPath: `Components/Design/index.ts`,
            isDirectory: false,
            isFile: true,
          },
        ],
        isDirectory: true,
        isFile: false,
      },
      {
        name: `Domain`,
        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain`,
        innerPath: `Components/Domain`,
        structure: [
          {
            name: `Bookmarks`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Bookmarks`,
            innerPath: `Components/Domain/Bookmarks`,
            structure: [
              {
                name: `Bookmark`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Bookmarks/Bookmark`,
                innerPath: `Components/Domain/Bookmarks/Bookmark`,
                structure: [
                  {
                    name: `index`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Bookmarks/Bookmark/index.tsx`,
                    innerPath: `Components/Domain/Bookmarks/Bookmark/index.tsx`,
                    isDirectory: false,
                    isFile: true,
                  },
                ],
                isDirectory: true,
                isFile: false,
              },
              {
                name: `BookmarksGrid`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Bookmarks/BookmarksGrid`,
                innerPath: `Components/Domain/Bookmarks/BookmarksGrid`,
                structure: [
                  {
                    name: `index`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Bookmarks/BookmarksGrid/index.tsx`,
                    innerPath: `Components/Domain/Bookmarks/BookmarksGrid/index.tsx`,
                    isDirectory: false,
                    isFile: true,
                  },
                ],
                isDirectory: true,
                isFile: false,
              },
              {
                name: `index`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Bookmarks/index.ts`,
                innerPath: `Components/Domain/Bookmarks/index.ts`,
                isDirectory: false,
                isFile: true,
              },
            ],
            isDirectory: true,
            isFile: false,
          },
          {
            name: `Flashcard`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Flashcard`,
            innerPath: `Components/Domain/Flashcard`,
            structure: [
              {
                name: `Flashcard`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Flashcard/Flashcard`,
                innerPath: `Components/Domain/Flashcard/Flashcard`,
                structure: [
                  {
                    name: `Flashcard`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Flashcard/Flashcard/Flashcard.tsx`,
                    innerPath: `Components/Domain/Flashcard/Flashcard/Flashcard.tsx`,
                    isDirectory: false,
                    isFile: true,
                  },
                  {
                    name: `duck`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Flashcard/Flashcard/duck`,
                    innerPath: `Components/Domain/Flashcard/Flashcard/duck`,
                    structure: [
                      {
                        name: `actions`,
                        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Flashcard/Flashcard/duck/actions.ts`,
                        innerPath: `Components/Domain/Flashcard/Flashcard/duck/actions.ts`,
                        isDirectory: false,
                        isFile: true,
                      },
                      {
                        name: `index`,
                        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Flashcard/Flashcard/duck/index.ts`,
                        innerPath: `Components/Domain/Flashcard/Flashcard/duck/index.ts`,
                        isDirectory: false,
                        isFile: true,
                      },
                      {
                        name: `reducers`,
                        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Flashcard/Flashcard/duck/reducers.ts`,
                        innerPath: `Components/Domain/Flashcard/Flashcard/duck/reducers.ts`,
                        isDirectory: false,
                        isFile: true,
                      },
                      {
                        name: `selectors`,
                        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Flashcard/Flashcard/duck/selectors.ts`,
                        innerPath: `Components/Domain/Flashcard/Flashcard/duck/selectors.ts`,
                        isDirectory: false,
                        isFile: true,
                      },
                      {
                        name: `thunks`,
                        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Flashcard/Flashcard/duck/thunks.ts`,
                        innerPath: `Components/Domain/Flashcard/Flashcard/duck/thunks.ts`,
                        isDirectory: false,
                        isFile: true,
                      },
                      {
                        name: `types`,
                        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Flashcard/Flashcard/duck/types.ts`,
                        innerPath: `Components/Domain/Flashcard/Flashcard/duck/types.ts`,
                        isDirectory: false,
                        isFile: true,
                      },
                      {
                        name: `utils`,
                        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Flashcard/Flashcard/duck/utils.ts`,
                        innerPath: `Components/Domain/Flashcard/Flashcard/duck/utils.ts`,
                        isDirectory: false,
                        isFile: true,
                      },
                    ],
                    isDirectory: true,
                    isFile: false,
                  },
                  {
                    name: `index`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Flashcard/Flashcard/index.ts`,
                    innerPath: `Components/Domain/Flashcard/Flashcard/index.ts`,
                    isDirectory: false,
                    isFile: true,
                  },
                ],
                isDirectory: true,
                isFile: false,
              },
              {
                name: `FlashcardQuiz`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Flashcard/FlashcardQuiz`,
                innerPath: `Components/Domain/Flashcard/FlashcardQuiz`,
                structure: [
                  {
                    name: `FlashcardQuiz`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Flashcard/FlashcardQuiz/FlashcardQuiz.tsx`,
                    innerPath: `Components/Domain/Flashcard/FlashcardQuiz/FlashcardQuiz.tsx`,
                    isDirectory: false,
                    isFile: true,
                  },
                  {
                    name: `duck`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Flashcard/FlashcardQuiz/duck`,
                    innerPath: `Components/Domain/Flashcard/FlashcardQuiz/duck`,
                    structure: [
                      {
                        name: `actions`,
                        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Flashcard/FlashcardQuiz/duck/actions.ts`,
                        innerPath: `Components/Domain/Flashcard/FlashcardQuiz/duck/actions.ts`,
                        isDirectory: false,
                        isFile: true,
                      },
                      {
                        name: `index`,
                        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Flashcard/FlashcardQuiz/duck/index.ts`,
                        innerPath: `Components/Domain/Flashcard/FlashcardQuiz/duck/index.ts`,
                        isDirectory: false,
                        isFile: true,
                      },
                      {
                        name: `reducers`,
                        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Flashcard/FlashcardQuiz/duck/reducers.ts`,
                        innerPath: `Components/Domain/Flashcard/FlashcardQuiz/duck/reducers.ts`,
                        isDirectory: false,
                        isFile: true,
                      },
                      {
                        name: `selectors`,
                        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Flashcard/FlashcardQuiz/duck/selectors.ts`,
                        innerPath: `Components/Domain/Flashcard/FlashcardQuiz/duck/selectors.ts`,
                        isDirectory: false,
                        isFile: true,
                      },
                      {
                        name: `thunks`,
                        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Flashcard/FlashcardQuiz/duck/thunks.ts`,
                        innerPath: `Components/Domain/Flashcard/FlashcardQuiz/duck/thunks.ts`,
                        isDirectory: false,
                        isFile: true,
                      },
                      {
                        name: `types`,
                        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Flashcard/FlashcardQuiz/duck/types.ts`,
                        innerPath: `Components/Domain/Flashcard/FlashcardQuiz/duck/types.ts`,
                        isDirectory: false,
                        isFile: true,
                      },
                      {
                        name: `utils`,
                        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Flashcard/FlashcardQuiz/duck/utils.ts`,
                        innerPath: `Components/Domain/Flashcard/FlashcardQuiz/duck/utils.ts`,
                        isDirectory: false,
                        isFile: true,
                      },
                    ],
                    isDirectory: true,
                    isFile: false,
                  },
                  {
                    name: `index`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Flashcard/FlashcardQuiz/index.ts`,
                    innerPath: `Components/Domain/Flashcard/FlashcardQuiz/index.ts`,
                    isDirectory: false,
                    isFile: true,
                  },
                  {
                    name: `stories`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Flashcard/FlashcardQuiz/stories`,
                    innerPath: `Components/Domain/Flashcard/FlashcardQuiz/stories`,
                    structure: [
                      {
                        name: `FlashcardQuiz`,
                        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Flashcard/FlashcardQuiz/stories/FlashcardQuiz.story.tsx`,
                        innerPath: `Components/Domain/Flashcard/FlashcardQuiz/stories/FlashcardQuiz.story.tsx`,
                        isDirectory: false,
                        isFile: true,
                      },
                    ],
                    isDirectory: true,
                    isFile: false,
                  },
                ],
                isDirectory: true,
                isFile: false,
              },
              {
                name: `index`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Flashcard/index.ts`,
                innerPath: `Components/Domain/Flashcard/index.ts`,
                isDirectory: false,
                isFile: true,
              },
            ],
            isDirectory: true,
            isFile: false,
          },
          {
            name: `Smite`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Smite`,
            innerPath: `Components/Domain/Smite`,
            structure: [
              {
                name: `GodPage`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Smite/GodPage`,
                innerPath: `Components/Domain/Smite/GodPage`,
                structure: [
                  {
                    name: `GodAbilities`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Smite/GodPage/GodAbilities`,
                    innerPath: `Components/Domain/Smite/GodPage/GodAbilities`,
                    structure: [
                      {
                        name: `GodAbilityImage`,
                        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Smite/GodPage/GodAbilities/GodAbilityImage.css`,
                        innerPath: `Components/Domain/Smite/GodPage/GodAbilities/GodAbilityImage.css`,
                        isDirectory: false,
                        isFile: true,
                      },
                      {
                        name: `GodAbilityImage`,
                        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Smite/GodPage/GodAbilities/GodAbilityImage.tsx`,
                        innerPath: `Components/Domain/Smite/GodPage/GodAbilities/GodAbilityImage.tsx`,
                        isDirectory: false,
                        isFile: true,
                      },
                      {
                        name: `GodAbilityInformation`,
                        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Smite/GodPage/GodAbilities/GodAbilityInformation.tsx`,
                        innerPath: `Components/Domain/Smite/GodPage/GodAbilities/GodAbilityInformation.tsx`,
                        isDirectory: false,
                        isFile: true,
                      },
                      {
                        name: `index`,
                        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Smite/GodPage/GodAbilities/index.tsx`,
                        innerPath: `Components/Domain/Smite/GodPage/GodAbilities/index.tsx`,
                        isDirectory: false,
                        isFile: true,
                      },
                    ],
                    isDirectory: true,
                    isFile: false,
                  },
                  {
                    name: `GodCard`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Smite/GodPage/GodCard.tsx`,
                    innerPath: `Components/Domain/Smite/GodPage/GodCard.tsx`,
                    isDirectory: false,
                    isFile: true,
                  },
                  {
                    name: `GodPage`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Smite/GodPage/GodPage.tsx`,
                    innerPath: `Components/Domain/Smite/GodPage/GodPage.tsx`,
                    isDirectory: false,
                    isFile: true,
                  },
                  {
                    name: `GodStats`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Smite/GodPage/GodStats`,
                    innerPath: `Components/Domain/Smite/GodPage/GodStats`,
                    structure: [
                      {
                        name: `index`,
                        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Smite/GodPage/GodStats/index.tsx`,
                        innerPath: `Components/Domain/Smite/GodPage/GodStats/index.tsx`,
                        isDirectory: false,
                        isFile: true,
                      },
                      {
                        name: `utils`,
                        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Smite/GodPage/GodStats/utils.ts`,
                        innerPath: `Components/Domain/Smite/GodPage/GodStats/utils.ts`,
                        isDirectory: false,
                        isFile: true,
                      },
                    ],
                    isDirectory: true,
                    isFile: false,
                  },
                  {
                    name: `index`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Smite/GodPage/index.tsx`,
                    innerPath: `Components/Domain/Smite/GodPage/index.tsx`,
                    isDirectory: false,
                    isFile: true,
                  },
                ],
                isDirectory: true,
                isFile: false,
              },
              {
                name: `GodsList`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Smite/GodsList`,
                innerPath: `Components/Domain/Smite/GodsList`,
                structure: [
                  {
                    name: `GodOnGodsList`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Smite/GodsList/GodOnGodsList`,
                    innerPath: `Components/Domain/Smite/GodsList/GodOnGodsList`,
                    structure: [
                      {
                        name: `index`,
                        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Smite/GodsList/GodOnGodsList/index.tsx`,
                        innerPath: `Components/Domain/Smite/GodsList/GodOnGodsList/index.tsx`,
                        isDirectory: false,
                        isFile: true,
                      },
                    ],
                    isDirectory: true,
                    isFile: false,
                  },
                  {
                    name: `GodsSearchBar`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Smite/GodsList/GodsSearchBar`,
                    innerPath: `Components/Domain/Smite/GodsList/GodsSearchBar`,
                    structure: [
                      {
                        name: `index`,
                        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Smite/GodsList/GodsSearchBar/index.tsx`,
                        innerPath: `Components/Domain/Smite/GodsList/GodsSearchBar/index.tsx`,
                        isDirectory: false,
                        isFile: true,
                      },
                    ],
                    isDirectory: true,
                    isFile: false,
                  },
                  {
                    name: `index`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Smite/GodsList/index.css`,
                    innerPath: `Components/Domain/Smite/GodsList/index.css`,
                    isDirectory: false,
                    isFile: true,
                  },
                  {
                    name: `index`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Smite/GodsList/index.tsx`,
                    innerPath: `Components/Domain/Smite/GodsList/index.tsx`,
                    isDirectory: false,
                    isFile: true,
                  },
                ],
                isDirectory: true,
                isFile: false,
              },
              {
                name: `index`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Smite/index.ts`,
                innerPath: `Components/Domain/Smite/index.ts`,
                isDirectory: false,
                isFile: true,
              },
            ],
            isDirectory: true,
            isFile: false,
          },
          {
            name: `Ukulele`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Ukulele`,
            innerPath: `Components/Domain/Ukulele`,
            structure: [
              {
                name: `Chord`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Ukulele/Chord`,
                innerPath: `Components/Domain/Ukulele/Chord`,
                structure: [
                  {
                    name: `Chord`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Ukulele/Chord/Chord.tsx`,
                    innerPath: `Components/Domain/Ukulele/Chord/Chord.tsx`,
                    isDirectory: false,
                    isFile: true,
                  },
                  {
                    name: `index`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Ukulele/Chord/index.ts`,
                    innerPath: `Components/Domain/Ukulele/Chord/index.ts`,
                    isDirectory: false,
                    isFile: true,
                  },
                  {
                    name: `types`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Ukulele/Chord/types.ts`,
                    innerPath: `Components/Domain/Ukulele/Chord/types.ts`,
                    isDirectory: false,
                    isFile: true,
                  },
                  {
                    name: `utils`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Ukulele/Chord/utils.ts`,
                    innerPath: `Components/Domain/Ukulele/Chord/utils.ts`,
                    isDirectory: false,
                    isFile: true,
                  },
                ],
                isDirectory: true,
                isFile: false,
              },
              {
                name: `Ukulele`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Ukulele/Ukulele.tsx`,
                innerPath: `Components/Domain/Ukulele/Ukulele.tsx`,
                isDirectory: false,
                isFile: true,
              },
              {
                name: `index`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/Ukulele/index.tsx`,
                innerPath: `Components/Domain/Ukulele/index.tsx`,
                isDirectory: false,
                isFile: true,
              },
            ],
            isDirectory: true,
            isFile: false,
          },
          {
            name: `index`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Domain/index.ts`,
            innerPath: `Components/Domain/index.ts`,
            isDirectory: false,
            isFile: true,
          },
        ],
        isDirectory: true,
        isFile: false,
      },
      {
        name: `Routes`,
        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Routes`,
        innerPath: `Components/Routes`,
        structure: [
          {
            name: `BookmarksRoute`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Routes/BookmarksRoute`,
            innerPath: `Components/Routes/BookmarksRoute`,
            structure: [
              {
                name: `index`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Routes/BookmarksRoute/index.tsx`,
                innerPath: `Components/Routes/BookmarksRoute/index.tsx`,
                isDirectory: false,
                isFile: true,
              },
            ],
            isDirectory: true,
            isFile: false,
          },
          {
            name: `FlashcardsRoute`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Routes/FlashcardsRoute`,
            innerPath: `Components/Routes/FlashcardsRoute`,
            structure: [
              {
                name: `Data`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Routes/FlashcardsRoute/Data`,
                innerPath: `Components/Routes/FlashcardsRoute/Data`,
                structure: [
                  {
                    name: `Data`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Routes/FlashcardsRoute/Data/Data.ts`,
                    innerPath: `Components/Routes/FlashcardsRoute/Data/Data.ts`,
                    isDirectory: false,
                    isFile: true,
                  },
                  {
                    name: `index`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Routes/FlashcardsRoute/Data/index.ts`,
                    innerPath: `Components/Routes/FlashcardsRoute/Data/index.ts`,
                    isDirectory: false,
                    isFile: true,
                  },
                  {
                    name: `temporaryHold`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Routes/FlashcardsRoute/Data/temporaryHold.js`,
                    innerPath: `Components/Routes/FlashcardsRoute/Data/temporaryHold.js`,
                    isDirectory: false,
                    isFile: true,
                  },
                ],
                isDirectory: true,
                isFile: false,
              },
              {
                name: `Flashcard`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Routes/FlashcardsRoute/Flashcard`,
                innerPath: `Components/Routes/FlashcardsRoute/Flashcard`,
                structure: [
                  {
                    name: `Flashcard`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Routes/FlashcardsRoute/Flashcard/Flashcard.tsx`,
                    innerPath: `Components/Routes/FlashcardsRoute/Flashcard/Flashcard.tsx`,
                    isDirectory: false,
                    isFile: true,
                  },
                  {
                    name: `index`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Routes/FlashcardsRoute/Flashcard/index.ts`,
                    innerPath: `Components/Routes/FlashcardsRoute/Flashcard/index.ts`,
                    isDirectory: false,
                    isFile: true,
                  },
                ],
                isDirectory: true,
                isFile: false,
              },
              {
                name: `FlashcardQuiz`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Routes/FlashcardsRoute/FlashcardQuiz`,
                innerPath: `Components/Routes/FlashcardsRoute/FlashcardQuiz`,
                structure: [
                  {
                    name: `FlashcardQuiz`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Routes/FlashcardsRoute/FlashcardQuiz/FlashcardQuiz.tsx`,
                    innerPath: `Components/Routes/FlashcardsRoute/FlashcardQuiz/FlashcardQuiz.tsx`,
                    isDirectory: false,
                    isFile: true,
                  },
                  {
                    name: `calculateGrade`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Routes/FlashcardsRoute/FlashcardQuiz/calculateGrade.ts`,
                    innerPath: `Components/Routes/FlashcardsRoute/FlashcardQuiz/calculateGrade.ts`,
                    isDirectory: false,
                    isFile: true,
                  },
                  {
                    name: `index`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Routes/FlashcardsRoute/FlashcardQuiz/index.ts`,
                    innerPath: `Components/Routes/FlashcardsRoute/FlashcardQuiz/index.ts`,
                    isDirectory: false,
                    isFile: true,
                  },
                ],
                isDirectory: true,
                isFile: false,
              },
              {
                name: `FlashcardSetSelection`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Routes/FlashcardsRoute/FlashcardSetSelection`,
                innerPath: `Components/Routes/FlashcardsRoute/FlashcardSetSelection`,
                structure: [
                  {
                    name: `FlashcardSetSelection`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Routes/FlashcardsRoute/FlashcardSetSelection/FlashcardSetSelection.tsx`,
                    innerPath: `Components/Routes/FlashcardsRoute/FlashcardSetSelection/FlashcardSetSelection.tsx`,
                    isDirectory: false,
                    isFile: true,
                  },
                  {
                    name: `FlashcardSetSelectionEachOne`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Routes/FlashcardsRoute/FlashcardSetSelection/FlashcardSetSelectionEachOne.tsx`,
                    innerPath: `Components/Routes/FlashcardsRoute/FlashcardSetSelection/FlashcardSetSelectionEachOne.tsx`,
                    isDirectory: false,
                    isFile: true,
                  },
                  {
                    name: `index`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Routes/FlashcardsRoute/FlashcardSetSelection/index.ts`,
                    innerPath: `Components/Routes/FlashcardsRoute/FlashcardSetSelection/index.ts`,
                    isDirectory: false,
                    isFile: true,
                  },
                ],
                isDirectory: true,
                isFile: false,
              },
              {
                name: `FlashcardsRoute`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Routes/FlashcardsRoute/FlashcardsRoute.tsx`,
                innerPath: `Components/Routes/FlashcardsRoute/FlashcardsRoute.tsx`,
                isDirectory: false,
                isFile: true,
              },
              {
                name: `index`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Routes/FlashcardsRoute/index.ts`,
                innerPath: `Components/Routes/FlashcardsRoute/index.ts`,
                isDirectory: false,
                isFile: true,
              },
            ],
            isDirectory: true,
            isFile: false,
          },
          {
            name: `SmiteRoute`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Routes/SmiteRoute`,
            innerPath: `Components/Routes/SmiteRoute`,
            structure: [
              {
                name: `index`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Routes/SmiteRoute/index.css`,
                innerPath: `Components/Routes/SmiteRoute/index.css`,
                isDirectory: false,
                isFile: true,
              },
              {
                name: `index`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Routes/SmiteRoute/index.tsx`,
                innerPath: `Components/Routes/SmiteRoute/index.tsx`,
                isDirectory: false,
                isFile: true,
              },
            ],
            isDirectory: true,
            isFile: false,
          },
          {
            name: `index`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Components/Routes/index.tsx`,
            innerPath: `Components/Routes/index.tsx`,
            isDirectory: false,
            isFile: true,
          },
        ],
        isDirectory: true,
        isFile: false,
      },
    ],
    isDirectory: true,
    isFile: false,
  },
  {
    name: `Constants`,
    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Constants`,
    innerPath: `Constants`,
    structure: [],
    isDirectory: true,
    isFile: false,
  },
  {
    name: `Hocs`,
    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Hocs`,
    innerPath: `Hocs`,
    structure: [],
    isDirectory: true,
    isFile: false,
  },
  {
    name: `Redux`,
    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux`,
    innerPath: `Redux`,
    structure: [
      {
        name: `flashcard`,
        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/flashcard`,
        innerPath: `Redux/flashcard`,
        structure: [
          {
            name: `__tests__`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/flashcard/__tests__`,
            innerPath: `Redux/flashcard/__tests__`,
            structure: [
              {
                name: `__snapshots__`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/flashcard/__tests__/__snapshots__`,
                innerPath: `Redux/flashcard/__tests__/__snapshots__`,
                structure: [
                  {
                    name: `selectors`,
                    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/flashcard/__tests__/__snapshots__/selectors.test.ts.snap`,
                    innerPath: `Redux/flashcard/__tests__/__snapshots__/selectors.test.ts.snap`,
                    isDirectory: false,
                    isFile: true,
                  },
                ],
                isDirectory: true,
                isFile: false,
              },
              {
                name: `mockData`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/flashcard/__tests__/mockData.ts`,
                innerPath: `Redux/flashcard/__tests__/mockData.ts`,
                isDirectory: false,
                isFile: true,
              },
              {
                name: `selectors`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/flashcard/__tests__/selectors.test.ts`,
                innerPath: `Redux/flashcard/__tests__/selectors.test.ts`,
                isDirectory: false,
                isFile: true,
              },
            ],
            isDirectory: true,
            isFile: false,
          },
          {
            name: `actions`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/flashcard/actions.ts`,
            innerPath: `Redux/flashcard/actions.ts`,
            isDirectory: false,
            isFile: true,
          },
          {
            name: `data`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/flashcard/data`,
            innerPath: `Redux/flashcard/data`,
            structure: [
              {
                name: `flexboxData`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/flashcard/data/flexboxData.ts`,
                innerPath: `Redux/flashcard/data/flexboxData.ts`,
                isDirectory: false,
                isFile: true,
              },
              {
                name: `index`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/flashcard/data/index.ts`,
                innerPath: `Redux/flashcard/data/index.ts`,
                isDirectory: false,
                isFile: true,
              },
              {
                name: `typescriptData`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/flashcard/data/typescriptData.ts`,
                innerPath: `Redux/flashcard/data/typescriptData.ts`,
                isDirectory: false,
                isFile: true,
              },
            ],
            isDirectory: true,
            isFile: false,
          },
          {
            name: `index`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/flashcard/index.ts`,
            innerPath: `Redux/flashcard/index.ts`,
            isDirectory: false,
            isFile: true,
          },
          {
            name: `reducers`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/flashcard/reducers.ts`,
            innerPath: `Redux/flashcard/reducers.ts`,
            isDirectory: false,
            isFile: true,
          },
          {
            name: `selectors`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/flashcard/selectors.ts`,
            innerPath: `Redux/flashcard/selectors.ts`,
            isDirectory: false,
            isFile: true,
          },
          {
            name: `types`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/flashcard/types.ts`,
            innerPath: `Redux/flashcard/types.ts`,
            isDirectory: false,
            isFile: true,
          },
        ],
        isDirectory: true,
        isFile: false,
      },
      {
        name: `index`,
        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/index.ts`,
        innerPath: `Redux/index.ts`,
        isDirectory: false,
        isFile: true,
      },
      {
        name: `smite`,
        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/smite`,
        innerPath: `Redux/smite`,
        structure: [
          {
            name: `actions`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/smite/actions.ts`,
            innerPath: `Redux/smite/actions.ts`,
            isDirectory: false,
            isFile: true,
          },
          {
            name: `data`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/smite/data`,
            innerPath: `Redux/smite/data`,
            structure: [
              {
                name: `Medusa`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/smite/data/Medusa.json`,
                innerPath: `Redux/smite/data/Medusa.json`,
                isDirectory: false,
                isFile: true,
              },
              {
                name: `artemis`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/smite/data/artemis.json`,
                innerPath: `Redux/smite/data/artemis.json`,
                isDirectory: false,
                isFile: true,
              },
              {
                name: `gods`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/smite/data/gods.ts`,
                innerPath: `Redux/smite/data/gods.ts`,
                isDirectory: false,
                isFile: true,
              },
              {
                name: `index`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/smite/data/index.ts`,
                innerPath: `Redux/smite/data/index.ts`,
                isDirectory: false,
                isFile: true,
              },
              {
                name: `items`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/smite/data/items.ts`,
                innerPath: `Redux/smite/data/items.ts`,
                isDirectory: false,
                isFile: true,
              },
            ],
            isDirectory: true,
            isFile: false,
          },
          {
            name: `index`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/smite/index.ts`,
            innerPath: `Redux/smite/index.ts`,
            isDirectory: false,
            isFile: true,
          },
          {
            name: `reducers`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/smite/reducers.ts`,
            innerPath: `Redux/smite/reducers.ts`,
            isDirectory: false,
            isFile: true,
          },
          {
            name: `selectors`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/smite/selectors.ts`,
            innerPath: `Redux/smite/selectors.ts`,
            isDirectory: false,
            isFile: true,
          },
          {
            name: `types`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/smite/types`,
            innerPath: `Redux/smite/types`,
            structure: [
              {
                name: `godData`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/smite/types/godData.ts`,
                innerPath: `Redux/smite/types/godData.ts`,
                isDirectory: false,
                isFile: true,
              },
              {
                name: `index`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/smite/types/index.ts`,
                innerPath: `Redux/smite/types/index.ts`,
                isDirectory: false,
                isFile: true,
              },
              {
                name: `itemData`,
                path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/smite/types/itemData.ts`,
                innerPath: `Redux/smite/types/itemData.ts`,
                isDirectory: false,
                isFile: true,
              },
            ],
            isDirectory: true,
            isFile: false,
          },
        ],
        isDirectory: true,
        isFile: false,
      },
      {
        name: `types`,
        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/types.ts`,
        innerPath: `Redux/types.ts`,
        isDirectory: false,
        isFile: true,
      },
      {
        name: `ui`,
        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/ui`,
        innerPath: `Redux/ui`,
        structure: [
          {
            name: `actions`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/ui/actions.ts`,
            innerPath: `Redux/ui/actions.ts`,
            isDirectory: false,
            isFile: true,
          },
          {
            name: `reducers`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/ui/reducers.ts`,
            innerPath: `Redux/ui/reducers.ts`,
            isDirectory: false,
            isFile: true,
          },
          {
            name: `selectors`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/ui/selectors.ts`,
            innerPath: `Redux/ui/selectors.ts`,
            isDirectory: false,
            isFile: true,
          },
          {
            name: `types`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Redux/ui/types.ts`,
            innerPath: `Redux/ui/types.ts`,
            isDirectory: false,
            isFile: true,
          },
        ],
        isDirectory: true,
        isFile: false,
      },
    ],
    isDirectory: true,
    isFile: false,
  },
  {
    name: `Utils`,
    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Utils`,
    innerPath: `Utils`,
    structure: [
      {
        name: `cx`,
        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Utils/cx`,
        innerPath: `Utils/cx`,
        structure: [
          {
            name: `index`,
            path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Utils/cx/index.ts`,
            innerPath: `Utils/cx/index.ts`,
            isDirectory: false,
            isFile: true,
          },
        ],
        isDirectory: true,
        isFile: false,
      },
      {
        name: `index`,
        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/Utils/index.ts`,
        innerPath: `Utils/index.ts`,
        isDirectory: false,
        isFile: true,
      },
    ],
    isDirectory: true,
    isFile: false,
  },
  {
    name: `__tests__`,
    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/__tests__`,
    innerPath: `__tests__`,
    structure: [
      {
        name: `exampleStructure`,
        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/__tests__/exampleStructure.ts`,
        innerPath: `__tests__/exampleStructure.ts`,
        isDirectory: false,
        isFile: true,
      },
      {
        name: `fileStructure`,
        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/__tests__/fileStructure.test.ts`,
        innerPath: `__tests__/fileStructure.test.ts`,
        isDirectory: false,
        isFile: true,
      },
      {
        name: `index`,
        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/__tests__/index.ts`,
        innerPath: `__tests__/index.ts`,
        isDirectory: false,
        isFile: true,
      },
      {
        name: `testForTheTest`,
        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/__tests__/testForTheTest.test.ts`,
        innerPath: `__tests__/testForTheTest.test.ts`,
        isDirectory: false,
        isFile: true,
      },
      {
        name: `types`,
        path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/__tests__/types.ts`,
        innerPath: `__tests__/types.ts`,
        isDirectory: false,
        isFile: true,
      },
    ],
    isDirectory: true,
    isFile: false,
  },
  {
    name: `index`,
    path: `/Users/joshclyde/stuff/repos/all-the-things-ui/src/index.tsx`,
    innerPath: `index.tsx`,
    isDirectory: false,
    isFile: true,
  },
];
